name: Test PRs

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build the site
      run: |
        gem install bundler
        bundle config path vendor/bundle
        echo "   [debug] Current time A:" $(date +"%T")
        bundle install
        echo "   [debug] Current time B:" $(date +"%T")
        bundle exec jekyll build
        echo "   [debug] Current time C:" $(date +"%T")
    - name: Test the HTML
      run: bash scripts/test/html_proofer_staging.sh
